name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.2'

      - name: Initialize
        run: terraform init

      - name: Validate configuration
        run: terraform validate

      - name: Plan changes
        run: terraform plan -var "name=Julia"

      - name: Apply changes
        run: terraform apply -var "name=Julia" --auto-approve
        env:
          TF_IN_AUTOMATION: "true"